"""Source-backed documentation generation helpers."""

from __future__ import annotations

import json
from importlib.resources import files
from pathlib import Path
from typing import Any

from .metadata import capabilities


FIT_CONFIG_SCHEMA_FILENAME = "fit-config.schema.json"
TASK_GRAPH_SCHEMA_FILENAME = "task-graph.schema.json"


def markdown_table(headers: list[str], rows: list[list[Any]]) -> list[str]:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(str(value) for value in row) + " |")
    return lines


def generate_capabilities_markdown(*, phases: int = 16) -> str:
    """Generate the source-backed capabilities reference page."""

    caps = capabilities(phases=phases)
    lines = [
        "# Capabilities Reference",
        "",
        "<!-- Generated by `arti docs generate`. Do not edit by hand. -->",
        "",
        f"Generated from `arti.capabilities(phases={phases})`.",
        "",
        "## Profiles",
        "",
    ]
    profile_rows = []
    for name, profile in sorted(caps["profiles"].items()):
        profile_rows.append(
            [
                f"`{name}`",
                f"`{profile['observer_phase']}`",
                f"`{profile['virtual_recall']}`",
                f"`{profile['coord_dim']}`",
                f"`{profile['coord_frame_mode']}`",
            ]
        )
    lines.extend(markdown_table(["Name", "Observer Phase", "Virtual Recall", "Coord Dim", "Coord Frame"], profile_rows))
    lines.extend(["", "## Scales", ""])
    scale_rows = []
    for name, scale in sorted(caps["scales"].items()):
        scale_rows.append(
            [
                f"`{name}`",
                f"`{scale['hidden_multiplier']}`",
                f"`{scale['operator_count']}`",
                f"`{scale['interface_slots']}`",
                f"`{scale['recall_slots']}`",
                f"`{scale['recall_steps']}`",
                f"`{scale['recall_activation']}`",
            ]
        )
    lines.extend(markdown_table(["Name", "Hidden Multiplier", "Operators", "Interface Slots", "Recall Slots", "Recall Steps", "Recall Activation"], scale_rows))
    lines.extend(["", "## Plugins", ""])
    plugin_rows = []
    for name, plugin in sorted(caps["plugins"].items()):
        plugin_rows.append(
            [
                f"`{name}`",
                f"`{plugin['kind']}`",
                f"`{plugin['available']}`",
                ", ".join(f"`{item}`" for item in plugin["capabilities"]),
            ]
        )
    lines.extend(markdown_table(["Name", "Kind", "Available", "Capabilities"], plugin_rows))
    lines.extend(
        [
            "",
            "## Raw JSON",
            "",
            "```json",
            json.dumps(caps, indent=2, sort_keys=True),
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def generate_fit_config_schema() -> dict[str, Any]:
    """Generate a JSON Schema for declarative ARTI fit configs."""

    profile_names = sorted(capabilities()["profiles"])
    scale_names = sorted(capabilities()["scales"])
    plugin_names = sorted(capabilities()["plugins"])
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://arti.local/schemas/fit-config.schema.json",
        "title": "ARTI Fit Project Config",
        "type": "object",
        "additionalProperties": True,
        "properties": {
            "plugins": {"type": "array", "items": {"type": "string", "enum": plugin_names}},
            "profile": {"type": "string", "enum": profile_names},
            "phases": {"type": ["integer", "null"], "minimum": 0},
            "scale": {"type": "string", "enum": scale_names},
            "fit": {
                "type": "object",
                "additionalProperties": True,
                "properties": {
                    "plugins": {"type": "array", "items": {"type": "string", "enum": plugin_names}},
                    "profile": {"type": "string", "enum": profile_names},
                    "phases": {"type": ["integer", "null"], "minimum": 0},
                    "scale": {"type": "string", "enum": scale_names},
                    "objectives": {"type": "array", "items": {"type": "string", "enum": ["preserve-output", "task-fit", "validate"]}},
                    "objective": {"type": ["string", "array"], "items": {"type": "string", "enum": ["preserve-output", "task-fit", "validate"]}},
                    "target_modules": {"type": ["string", "array"], "items": {"type": "string"}},
                    "causal": {"type": "boolean"},
                },
            },
            "mechanism": {
                "type": "object",
                "additionalProperties": False,
                "properties": {
                    "coord_dim": {"type": ["integer", "null"], "minimum": 0},
                    "coord_frame_mode": {"type": ["string", "null"], "enum": ["none", "paired_rotation", "operator_bank", None]},
                    "observer_phase": {"type": ["boolean", "null"]},
                    "virtual_recall": {"type": ["boolean", "null"]},
                    "operator_count": {"type": ["integer", "null"], "minimum": 1},
                    "interface_slots": {"type": ["integer", "null"], "minimum": 1},
                    "recall_slots": {"type": ["integer", "null"], "minimum": 1},
                    "recall_steps": {"type": ["integer", "null"], "minimum": 0},
                    "recall_activation": {"type": ["string", "null"], "enum": ["half", "none", None]},
                    "hidden_multiplier": {"type": ["number", "null"], "exclusiveMinimum": 0},
                },
            },
            "runtime": {
                "type": "object",
                "additionalProperties": False,
                "properties": {
                    "causal": {"type": "boolean"},
                    "mask_key": {"type": ["string", "null"]},
                    "coord_key": {"type": ["string", "null"]},
                    "observer_coord_key": {"type": ["string", "null"]},
                    "frame_operators_key": {"type": ["string", "null"]},
                },
            },
            "insertion": {
                "type": "object",
                "additionalProperties": False,
                "properties": {
                    "where": {"type": ["string", "array", "null"], "items": {"type": "string"}},
                    "every": {"type": "integer", "minimum": 1},
                    "freeze_base": {"type": "boolean"},
                    "max_adapters": {"type": ["integer", "null"], "minimum": 0},
                    "max_extra_params": {
                        "oneOf": [
                            {"type": "integer", "minimum": 0},
                            {"type": "string", "pattern": r"^([0-9]+(_[0-9]+)*|[0-9]+(\.[0-9]+)?%)$"},
                            {"type": "null"},
                        ]
                    },
                },
            },
            "objectives": {"type": ["string", "array"], "items": {"type": "string", "enum": ["preserve-output", "task-fit", "validate"]}},
            "objective": {"type": ["string", "array"], "items": {"type": "string", "enum": ["preserve-output", "task-fit", "validate"]}},
        },
    }


def generate_fit_config_schema_json() -> str:
    """Generate the ARTI fit config JSON Schema document."""

    return json.dumps(generate_fit_config_schema(), indent=2, sort_keys=True) + "\n"


def generate_task_graph_schema() -> dict[str, Any]:
    """Generate a JSON Schema for ARTI task graph artifacts."""

    task_schema = {
        "type": "object",
        "additionalProperties": True,
        "required": ["name", "kind", "depends_on"],
        "properties": {
            "name": {"type": "string", "minLength": 1},
            "kind": {"type": "string", "minLength": 1},
            "depends_on": {"type": "array", "items": {"type": "string"}},
            "enabled": {"type": "boolean"},
            "status": {"type": "string"},
        },
    }
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://arti.local/schemas/task-graph.schema.json",
        "title": "ARTI Task Graph Artifact",
        "type": "object",
        "additionalProperties": False,
        "required": ["format_version", "package_name", "kind", "command_kind", "task_graph"],
        "properties": {
            "format_version": {"const": 1},
            "package_name": {"const": "arti"},
            "kind": {"const": "task-graph"},
            "command_kind": {"type": "string", "enum": ["build", "apply"]},
            "task_graph": {
                "type": "object",
                "additionalProperties": False,
                "required": ["tasks", "artifacts"],
                "properties": {
                    "tasks": {"type": "array", "minItems": 1, "items": task_schema},
                    "artifacts": {
                        "type": "object",
                        "additionalProperties": {"type": ["string", "null"]},
                    },
                },
            },
        },
    }


def generate_task_graph_schema_json() -> str:
    """Generate the ARTI task graph JSON Schema document."""

    return json.dumps(generate_task_graph_schema(), indent=2, sort_keys=True) + "\n"


def packaged_fit_config_schema_json() -> str:
    """Read the fit config JSON Schema bundled inside the installed package."""

    try:
        return files("arti").joinpath("schemas", FIT_CONFIG_SCHEMA_FILENAME).read_text(encoding="utf-8")
    except FileNotFoundError:
        return generate_fit_config_schema_json()


def packaged_task_graph_schema_json() -> str:
    """Read the task graph JSON Schema bundled inside the installed package."""

    try:
        return files("arti").joinpath("schemas", TASK_GRAPH_SCHEMA_FILENAME).read_text(encoding="utf-8")
    except FileNotFoundError:
        return generate_task_graph_schema_json()


def write_generated_docs(path: str | Path, *, phases: int = 16) -> Path:
    """Write generated docs and return the output path."""

    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(generate_capabilities_markdown(phases=phases), encoding="utf-8")
    return target


def write_fit_config_schema(path: str | Path) -> Path:
    """Write the generated fit config JSON Schema and return its path."""

    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(generate_fit_config_schema_json(), encoding="utf-8")
    return target


def write_task_graph_schema(path: str | Path) -> Path:
    """Write the generated task graph JSON Schema and return its path."""

    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(generate_task_graph_schema_json(), encoding="utf-8")
    return target


def check_generated_docs(path: str | Path, *, phases: int = 16) -> None:
    """Raise if generated docs are missing or stale."""

    target = Path(path)
    expected = generate_capabilities_markdown(phases=phases)
    existing = target.read_text(encoding="utf-8") if target.exists() else None
    if existing != expected:
        raise ValueError(f"generated docs are out of date: {target}")


def check_fit_config_schema(path: str | Path) -> None:
    """Raise if the generated fit config schema is missing or stale."""

    target = Path(path)
    expected = generate_fit_config_schema_json()
    existing = target.read_text(encoding="utf-8") if target.exists() else None
    if existing != expected:
        raise ValueError(f"generated fit config schema is out of date: {target}")


def check_task_graph_schema(path: str | Path) -> None:
    """Raise if the generated task graph schema is missing or stale."""

    target = Path(path)
    expected = generate_task_graph_schema_json()
    existing = target.read_text(encoding="utf-8") if target.exists() else None
    if existing != expected:
        raise ValueError(f"generated task graph schema is out of date: {target}")
