from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import arti
import pytest


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "generate_docs.py"
SPEC = importlib.util.spec_from_file_location("generate_docs", SCRIPT)
assert SPEC is not None and SPEC.loader is not None
generate_docs = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = generate_docs
SPEC.loader.exec_module(generate_docs)


def test_generated_capabilities_docs_reflect_public_capabilities_api() -> None:
    content = generate_docs.generate_capabilities_markdown(phases=16)
    caps = arti.capabilities(phases=16)

    assert "Generated by scripts/generate_docs.py" in content
    for name in caps["profiles"]:
        assert f"`{name}`" in content
    for name in caps["scales"]:
        assert f"`{name}`" in content
    for name in caps["plugins"]:
        assert f"`{name}`" in content


def test_generated_capabilities_doc_file_is_current() -> None:
    expected = generate_docs.generate_capabilities_markdown(phases=16)
    actual = (ROOT / "docs" / "reference" / "capabilities.md").read_text(encoding="utf-8")

    assert actual == expected


def test_cli_docs_generate_and_check(tmp_path: Path, capsys) -> None:
    from arti.cli import main

    output_path = tmp_path / "capabilities.md"

    assert main(["docs", "generate", "--output", str(output_path), "--phases", "12"]) == 0
    generate_output = capsys.readouterr().out
    assert '"action": "generate"' in generate_output
    assert output_path.exists()
    assert "Generated from `arti.capabilities(phases=12)`" in output_path.read_text(encoding="utf-8")

    assert main(["docs", "check", "--output", str(output_path), "--phases", "12"]) == 0
    check_output = capsys.readouterr().out
    assert '"action": "check"' in check_output

    output_path.write_text("stale\n", encoding="utf-8")
    assert main(["docs", "check", "--output", str(output_path), "--phases", "12"]) == 1
    assert "out of date" in capsys.readouterr().err


def test_fit_config_schema_generation_and_check(tmp_path: Path, capsys) -> None:
    from arti.cli import main

    schema = arti.generate_fit_config_schema()

    assert schema["title"] == "ARTI Fit Project Config"
    assert "runtime" in schema["properties"]
    assert "mask_key" in schema["properties"]["runtime"]["properties"]
    assert "mechanism" in schema["properties"]
    assert "operator_count" in schema["properties"]["mechanism"]["properties"]
    assert arti.packaged_fit_config_schema_json() == arti.generate_fit_config_schema_json()

    output_path = tmp_path / "fit-config.schema.json"
    assert main(["schema", "fit-config", "generate", "--output", str(output_path)]) == 0
    generate_output = capsys.readouterr().out
    assert '"kind": "fit-config-schema"' in generate_output
    assert output_path.read_text(encoding="utf-8") == arti.generate_fit_config_schema_json()

    assert main(["schema", "fit-config", "check", "--output", str(output_path)]) == 0
    assert '"action": "check"' in capsys.readouterr().out

    output_path.write_text("{}\n", encoding="utf-8")
    assert main(["schema", "fit-config", "check", "--output", str(output_path)]) == 1
    assert "fit config schema is out of date" in capsys.readouterr().err


def test_task_graph_schema_generation_and_check(tmp_path: Path, capsys) -> None:
    from arti.cli import main

    schema = arti.generate_task_graph_schema()

    assert schema["title"] == "ARTI Task Graph Artifact"
    assert schema["properties"]["kind"]["const"] == "task-graph"
    assert "tasks" in schema["properties"]["task_graph"]["properties"]
    assert arti.packaged_task_graph_schema_json() == arti.generate_task_graph_schema_json()

    output_path = tmp_path / "task-graph.schema.json"
    assert main(["schema", "task-graph", "generate", "--output", str(output_path)]) == 0
    generate_output = capsys.readouterr().out
    assert '"kind": "task-graph-schema"' in generate_output
    assert output_path.read_text(encoding="utf-8") == arti.generate_task_graph_schema_json()

    assert main(["schema", "task-graph", "check", "--output", str(output_path)]) == 0
    assert '"action": "check"' in capsys.readouterr().out

    output_path.write_text("{}\n", encoding="utf-8")
    assert main(["schema", "task-graph", "check", "--output", str(output_path)]) == 1
    assert "task graph schema is out of date" in capsys.readouterr().err


def test_cli_gate_runs_docs_quality_gate(tmp_path: Path, capsys) -> None:
    pytest.importorskip("mkdocs")
    from arti.cli import main

    output_path = tmp_path / "quality_gate_docs.json"

    assert main(["gate", "docs", "--fail-fast", "--output", str(output_path)]) == 0
    output = capsys.readouterr().out
    assert '"kind": "quality-gate"' in output
    assert output_path.exists()
    assert output_path.with_suffix(".md").exists()


def test_cli_gate_accepts_qwen_reuse_and_mainline(tmp_path: Path, monkeypatch) -> None:
    from arti.cli import build_parser, run_quality_gate_report

    output_path = tmp_path / "quality_gate_qwen.json"
    captured = []

    class Result:
        returncode = 0
        stdout = "ok"
        stderr = ""

    def fake_run(command: list[str], *, capture_output: bool, text: bool) -> Result:
        captured.append(command)
        output_path.write_text('{"passed": true, "runs": []}', encoding="utf-8")
        return Result()

    monkeypatch.setattr("arti.cli.subprocess.run", fake_run)

    parser = build_parser()
    mainline_args = parser.parse_args(["gate", "mainline"])
    qwen_args = parser.parse_args(["gate", "qwen", "--reuse-passing-producers", "--fail-fast", "--output", str(output_path)])

    assert mainline_args.gates == ["mainline"]
    payload = run_quality_gate_report(qwen_args)

    assert payload["ok"] is True
    assert captured == [
        [
            sys.executable,
            "scripts/quality_gate.py",
            "qwen",
            "--fail-fast",
            "--reuse-passing-producers",
            "--output",
            str(output_path),
        ]
    ]
