import hashlib
import json
from pathlib import Path

import pytest
import torch
import torch.nn as nn

from arti.nn import Fold, Half, LearnedPulse
from arti.web import artifact_schema, export, render_typescript_contract


ROOT = Path(__file__).resolve().parents[1]


class GenericAffine(nn.Module):
    def forward(self, signal, gate):
        return {"result": signal * (1.0 + gate), "salience": gate.expand_as(signal)}


def _sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


@pytest.mark.parametrize(
    "module,inputs,output_shape",
    [
        (Half().eval(), {"x": torch.randn(2, 5, 4)}, ["batch", "tokens", 4]),
        (Fold(k=3, dim=4).eval(), {"x": torch.randn(2, 5, 4), "mask": torch.ones(2, 5)}, ["batch", 3, 4]),
        (LearnedPulse(k=3, dim=4).eval(), {"x": torch.randn(2, 5, 4), "q": torch.rand(2, 5, 1), "mask": torch.ones(2, 5)}, ["batch", 3, 4]),
    ],
)
def test_web_export_writes_hashed_artifact(tmp_path, module, inputs, output_shape):
    result = export(module, tmp_path / "layer-web", example_inputs=inputs)
    manifest = json.loads(result.manifest_path.read_text(encoding="utf-8"))
    lock = json.loads(result.lock_path.read_text(encoding="utf-8"))
    assert manifest["format"] == "arti.web"
    assert manifest["format_version"] == 2
    assert manifest["module"]["type"].endswith(type(module).__name__)
    assert manifest["outputs"][0]["shape"] == output_shape
    assert [item["name"] for item in manifest["inputs"]] == list(inputs)
    assert manifest["files"]["model.onnx"]["sha256"] == _sha256(result.model_path)
    assert lock["manifest"]["sha256"] == _sha256(result.manifest_path)


def test_web_export_accepts_generic_named_inputs_and_outputs(tmp_path):
    signal = torch.randn(2, 5, 4)
    gate = torch.rand(2, 5, 1)
    result = export(GenericAffine().eval(), tmp_path / "generic", example_inputs={"signal": signal, "gate": gate})
    manifest = json.loads(result.manifest_path.read_text(encoding="utf-8"))
    assert [item["name"] for item in manifest["inputs"]] == ["signal", "gate"]
    assert [item["name"] for item in manifest["outputs"]] == ["result", "salience"]
    assert manifest["module"]["type"].endswith("GenericAffine")


@pytest.mark.parametrize(
    "module,message",
    [
        (Half(stochastic=True).eval(), "stochastic Half"),
        (Fold(k=2, dim=4, mode="attention").eval(), "mode='soft'"),
        (Fold(k=2).eval(), "explicit dim"),
        (LearnedPulse(k=2, dim=4, fold_topk=2).eval(), "topk"),
    ],
)
def test_web_export_rejects_unsupported_modes(tmp_path, module, message):
    with pytest.raises(ValueError, match=message):
        export(module, tmp_path / "bad", example_inputs={"x": torch.randn(1, 3, 4)})


def test_web_export_requires_eval_float32_and_declared_inputs(tmp_path):
    with pytest.raises(ValueError, match="module.eval"):
        export(Half(), tmp_path / "training", example_inputs={"x": torch.randn(1, 3, 4)})
    with pytest.raises(ValueError, match="float32"):
        export(Half().eval(), tmp_path / "dtype", example_inputs={"x": torch.randn(1, 3, 4).double()})
    with pytest.raises(TypeError, match="unexpected keyword argument"):
        export(Half().eval(), tmp_path / "q", example_inputs={"x": torch.randn(1, 3, 4), "q": torch.ones(1, 3)})


def test_web_contract_schema_and_generated_types_are_python_owned():
    schema = artifact_schema()
    assert schema["properties"]["manifest"]["properties"]["format_version"] == {"const": 2}
    generated = render_typescript_contract()
    assert "Generated by arti.web.contract" in generated
    assert "format_version: 2" in generated
    assert (ROOT / "packages" / "web" / "src" / "generated" / "contract.ts").read_text(encoding="utf-8") == generated
