"""ARTI public API.

ARTI is a PyTorch-first latent tensor dynamics package. The root namespace
exports the supported 3.x surface for downstream projects: core ARTI layers,
activation/workspace modules, runtime vocabulary helpers, glyph/text tensor
renderers, participant context builders, membrane routing helpers, source
integrity utilities, fit/adaptation helpers, and backend diagnostics.

For new code, start with ``ARTILayer`` / ``ARTIResidualBlock`` for full ARTI
blocks, or ``Half`` / ``Fold`` / ``Pulse`` / ``Recall`` / ``RecallRefiner`` for standalone
neural-network-native mechanisms. ``Pulse`` is the default learned pulse layer;
``PulseCompressor`` is the legacy explicit pulse-id path.
"""

from ._version import __version__
from .backend import available_backends, planned_backends
from .component_graph import (
    COMPONENT_GRAPH_FORMAT,
    COMPONENT_GRAPH_VERSION,
    ComponentGraphError,
    component_closure_fingerprint,
    component_graph,
    validate_component_graph,
    verify_component_graph,
)
from .component_registry import (
    ComponentRef,
    component_catalog,
    component_ref,
    component_spec,
    get_component_registry,
    register_component,
    resolve_component,
)
from .attachment import ARTI, ARTIAttachment, ARTIAttachmentSummary, ARTIExpertSet, ARTILayerInfo, discover_layers
from .attachment_config import ARTIAttachConfig, ARTIAttachTrainingConfig, attach_config_from_dict, load_attach_config, validate_attach_lock, write_attach_config, write_attach_lock
from .attachment_training import ARTICheckpointCallback, ARTITrainingResult, ARTITrainingSession, model_loss_objective, recall_alignment_objective, resolve_attachment_objective
from .attachment_hub import ARTIDoctorReport, ARTIHubSaveResult, load_attachment_pretrained, save_attachment_pretrained
from .blocks import ARTIHostBridge, ARTIPooledBlock, ARTIResidualBlock, ARTISequenceBlock
from .config import ARTIConfig
from .conversation import ParticipantContextTensors, build_participant_context, last_non_assistant_participant
from .distinctness import LatentDistinctnessReport, assert_latent_distinct, latent_distinctness_report
from .fit import ADAPTER_STACK_FORMAT, ARTIFitResult, ARTIProject, AdapterArtifactManifest, AdapterInsertionPlan, BackendCapabilities, BatchSchema, BuildTaskSpec, FitPlugin, FitProjectConfig, FitReportSummary, FitTaskRecord, ForwardProfile, MechanismOverrides, MechanismSummary, ParameterSummary, RuntimeFieldConfig, TensorField, apply_adapter, apply_adapter_stack, apply_mechanism_overrides, attention_mask_to_visibility, backend_capabilities, capabilities, check_fit_config_schema, check_generated_docs, check_task_graph_schema, compile_adapter_hotpaths, create_build_lock, create_deployment_manifest, create_task_graph_payload, doctor_report, doctor_report_markdown, fit, generate_capabilities_markdown, generate_fit_config_schema, generate_fit_config_schema_json, generate_task_graph_schema, generate_task_graph_schema_json, get_plugin, infer_batch_schema, infer_objectives, list_plugins, list_profiles, list_scales, load_fit_config, packaged_fit_config_schema_json, packaged_task_graph_schema_json, plan_provenance_fingerprint, project, reset_recall_queries, resolve_fit_config_mechanism, resolve_objectives, set_adapter_scale, set_recall_refine_schedule, set_recall_refine_steps, template_fit_config, validate_artifact, validate_artifact_payload, validate_backend_capabilities, validate_build_lock, validate_deployment_manifest, validate_fit_config, validate_plan, validate_plan_payload, validate_task_graph, validate_task_graph_payload, write_doctor_report, write_fit_config_schema, write_fit_config_template, write_generated_docs, write_task_graph_artifact, write_task_graph_schema
from .fit import concatenate_adapter_banks, set_adapter_bank_influences, set_adapter_bank_weights
from .layers import (
    ARTIDynamicStateLayer,
    ARTILatentRecallField,
    ARTILatentTensorLayer,
    ARTILayer,
    ARTIPhaseMixer,
    ARTIVirtualInterfaceMixer,
)
from .inspection import InspectionReport, inspect
from .literal_decoder import LiteralSequenceDecoder, LiteralSequenceOutput
from .layered_recall import (
    LayerRecall,
    LayerRecallSpec,
    LayerRecallStack,
    LayerRecallWrapper,
    LayeredRecallCalibration,
    LayeredRecallConfig,
    LayeredRecallLoss,
    LayeredRecallModel,
    calibrate_layered_recall,
    layered_recall_trajectory_loss,
)
from .recall_topology import (
    LayeredRecallBudget,
    LayeredRecallCandidate,
    LayeredRecallCost,
    LayeredRecallScore,
    LayeredRecallTraceCache,
    candidates_within_budget,
    estimate_layered_recall_cost,
    pareto_layered_recall,
    screen_layered_recall_candidate,
)
from .literal_fit import LiteralFitResult, fit_literal_sequence
from .membrane import (
    MEMBRANE_STREAM_ASSISTANT_INNER,
    MEMBRANE_STREAM_ASSISTANT_PUBLIC,
    MEMBRANE_STREAM_NAMES,
    MembraneContext,
    MembraneRoutingConfig,
    MembraneRoutingOutput,
    MembraneVisibilityRouter,
    append_membrane_tokens,
    build_membrane_visibility,
    membrane_emit_tokens,
    membrane_public_emit_mask,
)
from .models import ARTIClassifier
from .nn import Fold, FusionPulse, Half, Layer, LearnedPulse, PixelShiftObservation, Pulse, Recall, RecallRefiner, StatefulRecall, UnFold, VisualField, VisualFieldOutput, VisualScan, VisualScanConfig, VisualScanOutput, concat_visual_fields
from .recall_formula import (
    FactorSpec,
    RecallFormulaContract,
    RecallFormulaExecutionSpec,
    RecallFormulaLock,
    formula_dtype_supported,
    validate_formula,
)
from .recall_registry import RecallFormulaId, describe_formula, list_formulas, register_formula
from .visual_scan import DEFAULT_PIXEL_SHIFTS, pixel_shift_observe, shift_and_add
from .outputs import ARTIOutput
from .pulse import PulseCompressor, PulseOutput, assert_pulse_distinct, fixed_width_pulse_ids, pulse_compress, pulse_distinctness_report
from .pretrained import ARTIPlan, ARTIPretrained, ComponentPlan, PretrainedExportResult, PretrainedFitResult, TrainingSpec, from_pretrained, model_structure_fingerprint, pretrained, validate_pretrained_lock
from .providers import ARTIProviderError, DiffusersProvider, PEFTProvider, PretrainedProvider, ProviderInspection, TorchProvider, TransformersProvider, get_provider as get_pretrained_provider, provider_report, register_provider
from .recall_artifacts import RECALL_ARTIFACT_KIND, RECALL_ARTIFACT_VERSION, RecallArtifactSpec, RecallCapacityDecision, RecallCapacityPlan, RecallExpertPool, RecallExpertRegistry, export_recall_artifact, load_recall_artifact, module_structure_fingerprint, recall_artifact_path
from .recall_experts import RECALL_BANK_ARTIFACT_KIND, RECALL_BANK_ARTIFACT_VERSION, RecallBankSpec, RecallExpertAsset, RecallExpertAssembly, RecallExpertContract, RecallExpertLayout, canonical_tensor_state_sha256, create_recall_expert_contract, export_recall_expert_bank, freeze_for_recall_expert, inspect_recall_expert_bank, load_recall_expert_bank, module_value_sha256, recall_bank_parameter_names, validate_recall_expert_contract
from .runtime_vocab import LiteralInput, LiteralOutputHead, LiteralVocabCache, LiteralVocabModel, OutputLexiconContext, RuntimeVocabEncoder, RuntimeVocabHead, RuntimeVocabInput, RuntimeVocabModel, RuntimeVocabPulseAdapter, attach_runtime_vocab_semantics, flatten_vocab_tensor, gather_runtime_vocab, permute_runtime_vocab, remap_token_ids
from .source_integrity import SOURCE_INTEGRITY_MODES, SourceIntegrityBasis, SourceIntegrityCarrier, SourceIntegrityReport, assert_source_integrity, decode_source_tokens, encode_source_tokens, make_source_integrity_basis, read_sources, source_basis_orthogonality_loss, source_integrity_loss, source_integrity_report, superpose_sources
from .serialization import ARTI_ST_FORMAT, ARTI_ST_FORMAT_VERSION, ARTILoadResult, ARTISaveResult, load, migrate_pt, save
from .text_bitmap import BitmapTextConfig, BitmapTextRenderer, BitmapVocabReport, assert_bitmap_vocab_distinct, bitmap_vocab_report, render_text_bitmap, render_text_vocab
from .text_tensor import TEXT_CONTROL_CHANNELS, TEXT_IDENTITY_MODES, TextControlKind, TextTensorConfig, TextTensorLayout, TextTensorRenderer, render_text_layout, render_text_tensor
from .tensor_boundary import TensorLayout
from .torch.cuda import cuda_device_report, cuda_runtime_available, cuda_smoke_report, require_cuda
from .training import experiential_recall_alignment_loss, experiential_recall_selectivity_loss, recall_route_exterior_penalty, virtual_recall_alignment_loss
from .usage import FeatureConfig, features, layer_profiles, profile

__all__ = [
    "ARTI",
    "ARTIAttachConfig",
    "ARTIAttachTrainingConfig",
    "ARTIAttachment",
    "ARTIAttachmentSummary",
    "ARTIExpertSet",
    "ARTILayerInfo",
    "discover_layers",
    "load_attach_config",
    "attach_config_from_dict",
    "write_attach_config",
    "write_attach_lock",
    "validate_attach_lock",
    "ARTITrainingSession",
    "ARTICheckpointCallback",
    "ARTITrainingResult",
    "ARTIDoctorReport",
    "ARTIHubSaveResult",
    "save_attachment_pretrained",
    "load_attachment_pretrained",
    "recall_alignment_objective",
    "model_loss_objective",
    "resolve_attachment_objective",
    "ARTIConfig",
    "TensorLayout",
    "ARTIOutput",
    "ARTILayer",
    "ARTILatentTensorLayer",
    "ARTIDynamicStateLayer",
    "ARTIVirtualInterfaceMixer",
    "ARTILatentRecallField",
    "Recall",
    "FactorSpec",
    "RecallFormulaId",
    "RecallFormulaContract",
    "RecallFormulaExecutionSpec",
    "RecallFormulaLock",
    "formula_dtype_supported",
    "validate_formula",
    "register_formula",
    "list_formulas",
    "describe_formula",
    "ARTIPhaseMixer",
    "ARTIResidualBlock",
    "ARTIHostBridge",
    "ARTISequenceBlock",
    "ARTIPooledBlock",
    "ARTIClassifier",
    "InspectionReport",
    "inspect",
    "LayerRecall",
    "LayerRecallWrapper",
    "LayeredRecallLoss",
    "LayerRecallSpec",
    "LayerRecallStack",
    "LayeredRecallConfig",
    "LayeredRecallCalibration",
    "LayeredRecallModel",
    "calibrate_layered_recall",
    "layered_recall_trajectory_loss",
    "LayeredRecallBudget",
    "LayeredRecallCandidate",
    "LayeredRecallCost",
    "LayeredRecallScore",
    "LayeredRecallTraceCache",
    "candidates_within_budget",
    "estimate_layered_recall_cost",
    "pareto_layered_recall",
    "screen_layered_recall_candidate",
    "Layer",
    "COMPONENT_GRAPH_FORMAT",
    "COMPONENT_GRAPH_VERSION",
    "ComponentGraphError",
    "component_closure_fingerprint",
    "component_graph",
    "validate_component_graph",
    "verify_component_graph",
    "ComponentRef",
    "component_catalog",
    "component_ref",
    "component_spec",
    "get_component_registry",
    "register_component",
    "resolve_component",
    "FeatureConfig",
    "features",
    "profile",
    "layer_profiles",
    "Half",
    "UnFold",
    "Fold",
    "Pulse",
    "LearnedPulse",
    "FusionPulse",
    "RecallRefiner",
    "StatefulRecall",
    "VisualField",
    "VisualFieldOutput",
    "concat_visual_fields",
    "VisualScan",
    "VisualScanConfig",
    "VisualScanOutput",
    "PixelShiftObservation",
    "DEFAULT_PIXEL_SHIFTS",
    "pixel_shift_observe",
    "shift_and_add",
    "ARTIPlan",
    "ARTIPretrained",
    "ComponentPlan",
    "TrainingSpec",
    "PretrainedFitResult",
    "PretrainedExportResult",
    "pretrained",
    "from_pretrained",
    "validate_pretrained_lock",
    "model_structure_fingerprint",
    "ARTIProviderError",
    "PretrainedProvider",
    "ProviderInspection",
    "TorchProvider",
    "TransformersProvider",
    "PEFTProvider",
    "DiffusersProvider",
    "register_provider",
    "get_pretrained_provider",
    "provider_report",
    "RECALL_ARTIFACT_KIND",
    "RECALL_ARTIFACT_VERSION",
    "RecallArtifactSpec",
    "RecallCapacityPlan",
    "RecallCapacityDecision",
    "RecallExpertRegistry",
    "RecallExpertPool",
    "module_structure_fingerprint",
    "recall_artifact_path",
    "export_recall_artifact",
    "load_recall_artifact",
    "RECALL_BANK_ARTIFACT_KIND",
    "RECALL_BANK_ARTIFACT_VERSION",
    "RecallBankSpec",
    "RecallExpertAsset",
    "RecallExpertAssembly",
    "RecallExpertContract",
    "RecallExpertLayout",
    "canonical_tensor_state_sha256",
    "create_recall_expert_contract",
    "export_recall_expert_bank",
    "freeze_for_recall_expert",
    "inspect_recall_expert_bank",
    "load_recall_expert_bank",
    "module_value_sha256",
    "recall_bank_parameter_names",
    "validate_recall_expert_contract",
    "MEMBRANE_STREAM_ASSISTANT_PUBLIC",
    "MEMBRANE_STREAM_ASSISTANT_INNER",
    "MEMBRANE_STREAM_NAMES",
    "MembraneRoutingConfig",
    "MembraneRoutingOutput",
    "MembraneContext",
    "MembraneVisibilityRouter",
    "membrane_public_emit_mask",
    "membrane_emit_tokens",
    "build_membrane_visibility",
    "append_membrane_tokens",
    "ParticipantContextTensors",
    "build_participant_context",
    "last_non_assistant_participant",
    "RuntimeVocabEncoder",
    "RuntimeVocabInput",
    "RuntimeVocabHead",
    "RuntimeVocabModel",
    "RuntimeVocabPulseAdapter",
    "LiteralVocabCache",
    "LiteralInput",
    "OutputLexiconContext",
    "LiteralOutputHead",
    "LiteralVocabModel",
    "LiteralSequenceDecoder",
    "LiteralSequenceOutput",
    "LiteralFitResult",
    "fit_literal_sequence",
    "attach_runtime_vocab_semantics",
    "flatten_vocab_tensor",
    "gather_runtime_vocab",
    "permute_runtime_vocab",
    "remap_token_ids",
    "PulseOutput",
    "PulseCompressor",
    "pulse_compress",
    "fixed_width_pulse_ids",
    "pulse_distinctness_report",
    "assert_pulse_distinct",
    "LatentDistinctnessReport",
    "latent_distinctness_report",
    "assert_latent_distinct",
    "BitmapTextConfig",
    "BitmapTextRenderer",
    "BitmapVocabReport",
    "render_text_bitmap",
    "render_text_vocab",
    "bitmap_vocab_report",
    "assert_bitmap_vocab_distinct",
    "TEXT_CONTROL_CHANNELS",
    "TEXT_IDENTITY_MODES",
    "TextControlKind",
    "TextTensorConfig",
    "TextTensorLayout",
    "TextTensorRenderer",
    "render_text_layout",
    "render_text_tensor",
    "SourceIntegrityBasis",
    "ARTI_ST_FORMAT",
    "ARTI_ST_FORMAT_VERSION",
    "ARTISaveResult",
    "ARTILoadResult",
    "save",
    "load",
    "migrate_pt",
    "SourceIntegrityCarrier",
    "SourceIntegrityReport",
    "SOURCE_INTEGRITY_MODES",
    "make_source_integrity_basis",
    "superpose_sources",
    "read_sources",
    "encode_source_tokens",
    "decode_source_tokens",
    "source_integrity_report",
    "source_integrity_loss",
    "assert_source_integrity",
    "source_basis_orthogonality_loss",
    "ARTIProject",
    "ARTIFitResult",
    "ADAPTER_STACK_FORMAT",
    "AdapterArtifactManifest",
    "BuildTaskSpec",
    "AdapterInsertionPlan",
    "FitPlugin",
    "FitProjectConfig",
    "MechanismOverrides",
    "RuntimeFieldConfig",
    "apply_mechanism_overrides",
    "resolve_fit_config_mechanism",
    "BackendCapabilities",
    "FitReportSummary",
    "FitTaskRecord",
    "ForwardProfile",
    "MechanismSummary",
    "ParameterSummary",
    "BatchSchema",
    "TensorField",
    "project",
    "reset_recall_queries",
    "fit",
    "apply_adapter",
    "apply_adapter_stack",
    "concatenate_adapter_banks",
    "set_adapter_bank_influences",
    "set_adapter_bank_weights",
    "compile_adapter_hotpaths",
    "set_adapter_scale",
    "set_recall_refine_schedule",
    "set_recall_refine_steps",
    "get_plugin",
    "load_fit_config",
    "template_fit_config",
    "validate_fit_config",
    "write_fit_config_template",
    "infer_batch_schema",
    "attention_mask_to_visibility",
    "capabilities",
    "list_profiles",
    "list_scales",
    "list_plugins",
    "resolve_objectives",
    "infer_objectives",
    "plan_provenance_fingerprint",
    "create_build_lock",
    "create_deployment_manifest",
    "create_task_graph_payload",
    "backend_capabilities",
    "doctor_report",
    "doctor_report_markdown",
    "validate_backend_capabilities",
    "write_doctor_report",
    "generate_capabilities_markdown",
    "generate_fit_config_schema",
    "generate_fit_config_schema_json",
    "generate_task_graph_schema",
    "generate_task_graph_schema_json",
    "packaged_fit_config_schema_json",
    "packaged_task_graph_schema_json",
    "write_generated_docs",
    "write_fit_config_schema",
    "write_task_graph_schema",
    "check_generated_docs",
    "check_fit_config_schema",
    "check_task_graph_schema",
    "validate_artifact",
    "validate_artifact_payload",
    "validate_build_lock",
    "validate_deployment_manifest",
    "validate_plan",
    "validate_plan_payload",
    "validate_task_graph",
    "validate_task_graph_payload",
    "write_task_graph_artifact",
    "cuda_device_report",
    "cuda_runtime_available",
    "cuda_smoke_report",
    "require_cuda",
    "virtual_recall_alignment_loss",
    "experiential_recall_alignment_loss",
    "recall_route_exterior_penalty",
    "experiential_recall_selectivity_loss",
    "available_backends",
    "planned_backends",
    "__version__",
]
