"""ARTI public API.

ARTI is a PyTorch-first latent tensor dynamics package. The root namespace
exports the stable mechanism surface for downstream projects: core ARTI layers,
activation/workspace modules, runtime vocabulary helpers, glyph/text tensor
renderers, participant context builders, membrane routing helpers, source
integrity utilities, fit/adaptation helpers, and backend diagnostics.

For new code, start with ``ARTILayer``. It is the federated-program host
boundary for configured query, local iteration, Formula Fabric, and traversal.
Standalone, versioned mechanisms live under ``arti.mechanisms``; retired APIs
live under ``arti.legacy``.
"""

from ._version import __version__
from . import experimental, legacy, mechanisms
from .backend import available_backends, planned_backends
from .attachment import ARTI, ARTIAttachment, ARTIAttachmentSummary, ARTILayerInfo, discover_layers
from .attachment_layer import AttachedARTILayerConfig, AttachedARTILayerSpec
from .attachment_config import ARTIAttachConfig, ARTIAttachTrainingConfig, attach_config_from_dict, load_attach_config, validate_attach_lock, write_attach_config, write_attach_lock
from .attachment_training import ARTICheckpointCallback, ARTITrainingResult, ARTITrainingSession, model_loss_objective, resolve_attachment_objective, tensor_alignment_objective
from .attachment_hub import ARTIDoctorReport, ARTIHubSaveResult, load_attachment_pretrained, save_attachment_pretrained
from .blocks import ARTIHostBridge, ARTIPooledBlock, ARTIResidualBlock, ARTISequenceBlock
from .config import ARTIConfig
from .component_registry import (
    COMPONENT_PROVENANCE_VERSION,
    COMPONENT_STATE_CONTRACT_VERSION,
    ComponentContract,
    ComponentCompatibilityError,
    ComponentRef,
    ComponentResolutionReceipt,
    ComponentRegistration,
    ComponentRegistry,
    ComponentRegistryError,
    ComponentSpec,
    DuplicateComponentError,
    InvalidComponentRefError,
    UnknownComponentError,
    canonical_contract_reference,
    component_graph_fingerprint,
    component_catalog,
    component_manifest,
    component_provenance,
    component_ref,
    component_spec,
    component_state_contract,
    get_component_registry,
    register_component,
    resolve_component,
    resolve_component_with_receipt,
    validate_component_provenance,
    validate_component_state_contract,
    verify_component_provenance,
    state_dict_schema,
)
from .component_graph import (
    COMPONENT_GRAPH_FORMAT,
    COMPONENT_GRAPH_VERSION,
    ComponentGraphError,
    component_closure_fingerprint,
    component_graph,
    validate_component_graph,
    verify_component_graph,
)
from .context import FrameContext, FrameMode, TensorContext, validate_valid_mask, validate_visibility
from .conversation import ParticipantContextTensors, build_participant_context, last_non_assistant_participant
from .distinctness import LatentDistinctnessReport, assert_latent_distinct, latent_distinctness_report
from .emission import EmissionRouter, EmissionRouterConfig, EmissionRouterOutput, build_stream_visibility, stream_emit_mask
from .fit import ADAPTER_STACK_FORMAT, ARTIFitResult, ARTIProject, AdapterArtifactManifest, AdapterInsertionPlan, BackendCapabilities, BatchSchema, BuildTaskSpec, FitPlugin, FitProjectConfig, FitReportSummary, FitTaskRecord, ForwardProfile, MechanismOverrides, MechanismSummary, ParameterSummary, RuntimeFieldConfig, TensorField, apply_adapter, apply_adapter_stack, apply_mechanism_overrides, attention_mask_to_visibility, backend_capabilities, capabilities, check_fit_config_schema, check_generated_docs, check_task_graph_schema, compile_adapter_hotpaths, create_build_lock, create_deployment_manifest, create_task_graph_payload, doctor_report, doctor_report_markdown, fit, generate_capabilities_markdown, generate_fit_config_schema, generate_fit_config_schema_json, generate_task_graph_schema, generate_task_graph_schema_json, get_plugin, infer_batch_schema, infer_objectives, list_plugins, list_profiles, list_scales, load_fit_config, packaged_fit_config_schema_json, packaged_task_graph_schema_json, plan_provenance_fingerprint, project, reset_recall_queries, resolve_fit_config_mechanism, resolve_objectives, set_adapter_scale, set_retrieval_iteration_schedule, set_retrieval_iteration_steps, template_fit_config, validate_artifact, validate_artifact_payload, validate_backend_capabilities, validate_build_lock, validate_deployment_manifest, validate_fit_config, validate_plan, validate_plan_payload, validate_task_graph, validate_task_graph_payload, write_doctor_report, write_fit_config_schema, write_fit_config_template, write_generated_docs, write_task_graph_artifact, write_task_graph_schema
from .fit import concatenate_adapter_banks, set_adapter_bank_influences, set_adapter_bank_weights
from .arti_layer import ARTILayer, ProgramLayerResult
from .layers import (
    ARTIDynamicStateLayer,
    ARTILatentRecallField,
    ARTILatentTensorLayer,
    ARTIPhaseMixer,
    ARTIVirtualInterfaceMixer,
)
from .inspection import InspectionReport, inspect
from .literal_decoder import LiteralSequenceDecoder, LiteralSequenceOutput
from .recall_topology import (
    LayeredRecallBudget,
    LayeredRecallCandidate,
    LayeredRecallCost,
    LayeredRecallScore,
    LayeredExecutionTraceCache,
    candidates_within_budget,
    estimate_layered_recall_cost,
    pareto_layered_recall,
    screen_layered_recall_candidate,
)
from .literal_fit import LiteralFitResult, fit_literal_sequence
from .membrane import (
    MEMBRANE_STREAM_ASSISTANT_INNER,
    MEMBRANE_STREAM_ASSISTANT_PUBLIC,
    MEMBRANE_STREAM_NAMES,
    MembraneContext,
    MembraneRoutingConfig,
    MembraneRoutingOutput,
    MembraneVisibilityRouter,
    append_membrane_tokens,
    build_membrane_visibility,
    membrane_emit_tokens,
    membrane_public_emit_mask,
)
from .models import ARTIClassifier
from .nn import Fold, FusionPulse, Half, Layer, LearnedPulse, PixelShiftObservation, Pulse, RecallExecutor, Retrieve, RetrieveExecutor, UnFold, VisualField, VisualFieldOutput, VisualScan, VisualScanConfig, VisualScanOutput, concat_visual_fields
from .recall_formula import (
    FactorSpec,
    RecallFormulaContract,
    RecallFormulaExecutionSpec,
    RecallFormulaLock,
    validate_formula,
)
from .recall_registry import RecallFormulaId, describe_formula, list_formulas, register_formula
from .execution import (
    EXECUTION_TRACE_SCHEMA_VERSION,
    EXECUTION_TRACE_V2_SCHEMA_VERSION,
    EXECUTION_TRACE_V3_SCHEMA_REF,
    EXECUTION_TRACE_V3_SCHEMA_VERSION,
    AdaptiveExecutionPolicy,
    ExecutionBudget,
    ExecutionPolicy,
    ExecutionStop,
    ExecutionStopReason,
    ExecutionTrace,
    ExecutionTraceV2,
    ExecutionTraceV3,
    RetrievalRoutePlan,
    RetrievalRouteStack,
)
from .visual_scan import DEFAULT_PIXEL_SHIFTS, pixel_shift_observe, shift_and_add
from .outputs import ARTIOutput
from .pulse import PulseCompressor, PulseOutput, assert_pulse_distinct, fixed_width_pulse_ids, pulse_compress, pulse_distinctness_report
from .pretrained import ARTIPlan, ARTIPretrained, ComponentPlan, PretrainedExportResult, PretrainedFitResult, TrainingSpec, from_pretrained, model_structure_fingerprint, pretrained, validate_pretrained_lock
from .providers import ARTIProviderError, DiffusersProvider, PEFTProvider, PretrainedProvider, ProviderInspection, TorchProvider, TransformersProvider, get_provider as get_pretrained_provider, provider_report, register_provider
from .recall_bank import RecallCapacityDecision, RecallCapacityPlan
from .recall_bank import RECALL_BANK_ARTIFACT_KIND, RECALL_BANK_ARTIFACT_VERSION, RECALL_BANK_PROVENANCE_VERSION, RecallBankAsset, RecallBankAssembly, RecallBankContract, RecallBankError, RecallBankLayout, RecallBankMember, RecallBankProvenance, canonical_tensor_state_sha256, create_recall_bank_contract, freeze_for_recall_bank, inspect_recall_bank, load_recall_bank, migrate_recall_bank, module_behavior_fingerprint, module_structure_fingerprint, module_value_sha256, recall_bank_parameter_names, save_recall_bank, validate_recall_bank_contract
from .runtime_vocab import LiteralInput, LiteralOutputHead, LiteralVocabCache, LiteralVocabModel, OutputLexiconContext, RuntimeVocabEncoder, RuntimeVocabHead, RuntimeVocabInput, RuntimeVocabModel, RuntimeVocabPulseAdapter, attach_runtime_vocab_semantics, flatten_vocab_tensor, gather_runtime_vocab, permute_runtime_vocab, remap_token_ids
from .source_integrity import SOURCE_INTEGRITY_MODES, SourceIntegrityBasis, SourceIntegrityCarrier, SourceIntegrityReport, assert_source_integrity, decode_source_tokens, encode_source_tokens, make_source_integrity_basis, read_sources, source_basis_orthogonality_loss, source_integrity_loss, source_integrity_report, superpose_sources
from .serialization import ARTI_ST_FORMAT, ARTI_ST_FORMAT_VERSION, ARTILoadResult, ARTISaveResult, load, save
from .survival import (
    DuplicateSurvivalError,
    ExponentialSurvival,
    InvalidSurvivalRefError,
    SurvivalContract,
    SurvivalDescription,
    SurvivalOperator,
    SurvivalRef,
    SurvivalRegistration,
    SurvivalRegistry,
    SurvivalRegistryError,
    UnknownSurvivalError,
    describe_survival,
    list_survivals,
    register_survival,
    resolve_survival,
    survival_is_registered,
    validate_survival_config,
)
from .text_bitmap import BitmapTextConfig, BitmapTextRenderer, BitmapVocabReport, assert_bitmap_vocab_distinct, bitmap_vocab_report, render_text_bitmap, render_text_vocab
from .text_tensor import TEXT_CONTROL_CHANNELS, TEXT_IDENTITY_MODES, TextControlKind, TextTensorConfig, TextTensorLayout, TextTensorRenderer, render_text_layout, render_text_tensor
from .tensor_boundary import TensorLayout
from .resource_graph import (
    PROGRAM_GRAPH_ARTIFACT_FORMAT,
    PROGRAM_GRAPH_ARTIFACT_VERSION,
    AxisRange,
    Connection,
    ConnectionExecution,
    FormulaTensorViewTransfer,
    LearnableAffineTransfer,
    StaticFormulaTensorViewTransfer,
    ProgramGraph,
    ProgramGraphExecution,
    ProgramGraphInvocation,
    ProgramGraphSaveResult,
    ProgramGraphState,
    ProgramNode,
    ProgramNodeExecution,
    ProgramNodeInvocation,
    ResourceBinding,
    ResourceGraphError,
    ResourceGraphCompileError,
    ResourceGraphCompiler,
    ResourceGraphExecutionPlan,
    ResourceLifetime,
    ResourcePort,
    ResourceSnapshot,
    ResourceView,
    TensorResource,
    TensorResourceSpec,
    TensorResourceState,
    load_program_graph,
    save_program_graph,
)
from .terminal_abi import (
    ProgramExecutionSignature,
    ProgramExecutionSignatureV2,
    ProgramExecutionSignatureV3,
)
from .torch.cuda import cuda_device_report, cuda_runtime_available, cuda_smoke_report, require_cuda
from .training import experiential_recall_alignment_loss, experiential_recall_selectivity_loss, recall_route_exterior_penalty, virtual_recall_alignment_loss
from .usage import FeatureConfig, features, layer_profiles, profile

# Compatibility name for previously recorded scripts and artifacts. New code
# should import the stable ``arti.mechanisms`` namespace.
alpha = mechanisms

__all__ = [
    "ARTI",
    "mechanisms",
    "alpha",
    "legacy",
    "experimental",
    "ARTIAttachConfig",
    "ARTIAttachTrainingConfig",
    "ARTIAttachment",
    "ARTIAttachmentSummary",
    "AttachedARTILayerConfig",
    "AttachedARTILayerSpec",
    "ARTILayerInfo",
    "discover_layers",
    "load_attach_config",
    "attach_config_from_dict",
    "write_attach_config",
    "write_attach_lock",
    "validate_attach_lock",
    "ARTITrainingSession",
    "ARTICheckpointCallback",
    "ARTITrainingResult",
    "ARTIDoctorReport",
    "ARTIHubSaveResult",
    "save_attachment_pretrained",
    "load_attachment_pretrained",
    "tensor_alignment_objective",
    "model_loss_objective",
    "resolve_attachment_objective",
    "ARTIConfig",
    "COMPONENT_PROVENANCE_VERSION",
    "COMPONENT_STATE_CONTRACT_VERSION",
    "ComponentContract",
    "ComponentCompatibilityError",
    "ComponentRef",
    "ComponentResolutionReceipt",
    "ComponentRegistration",
    "ComponentRegistry",
    "ComponentRegistryError",
    "ComponentSpec",
    "DuplicateComponentError",
    "InvalidComponentRefError",
    "UnknownComponentError",
    "canonical_contract_reference",
    "component_graph_fingerprint",
    "component_catalog",
    "component_manifest",
    "component_provenance",
    "component_ref",
    "component_spec",
    "component_state_contract",
    "get_component_registry",
    "register_component",
    "EXECUTION_TRACE_SCHEMA_VERSION",
    "RetrievalRoutePlan",
    "RetrievalRouteStack",
    "ExecutionStopReason",
    "ExecutionTrace",
    "ExecutionTraceV2",
    "ExecutionTraceV3",
    "ExecutionPolicy",
    "AdaptiveExecutionPolicy",
    "ExecutionBudget",
    "ExecutionStop",
    "EXECUTION_TRACE_V2_SCHEMA_VERSION",
    "EXECUTION_TRACE_V3_SCHEMA_REF",
    "EXECUTION_TRACE_V3_SCHEMA_VERSION",
    "resolve_component",
    "resolve_component_with_receipt",
    "validate_component_provenance",
    "validate_component_state_contract",
    "verify_component_provenance",
    "state_dict_schema",
    "COMPONENT_GRAPH_FORMAT",
    "COMPONENT_GRAPH_VERSION",
    "ComponentGraphError",
    "component_closure_fingerprint",
    "component_graph",
    "validate_component_graph",
    "verify_component_graph",
    "DuplicateSurvivalError",
    "ExponentialSurvival",
    "InvalidSurvivalRefError",
    "SurvivalContract",
    "SurvivalDescription",
    "SurvivalOperator",
    "SurvivalRef",
    "SurvivalRegistration",
    "SurvivalRegistry",
    "SurvivalRegistryError",
    "UnknownSurvivalError",
    "describe_survival",
    "list_survivals",
    "register_survival",
    "resolve_survival",
    "survival_is_registered",
    "validate_survival_config",
    "FrameContext",
    "FrameMode",
    "TensorContext",
    "validate_valid_mask",
    "validate_visibility",
    "TensorLayout",
    "Connection",
    "ConnectionExecution",
    "FormulaTensorViewTransfer",
    "LearnableAffineTransfer",
    "StaticFormulaTensorViewTransfer",
    "AxisRange",
    "ProgramGraph",
    "ProgramGraphExecution",
    "ProgramGraphInvocation",
    "ProgramGraphSaveResult",
    "PROGRAM_GRAPH_ARTIFACT_FORMAT",
    "PROGRAM_GRAPH_ARTIFACT_VERSION",
    "ProgramGraphState",
    "ProgramNode",
    "ProgramNodeExecution",
    "ProgramNodeInvocation",
    "ResourceBinding",
    "ResourceGraphError",
    "ResourceGraphCompileError",
    "ResourceGraphCompiler",
    "ResourceGraphExecutionPlan",
    "ResourceLifetime",
    "ResourcePort",
    "ResourceSnapshot",
    "ResourceView",
    "TensorResource",
    "TensorResourceSpec",
    "TensorResourceState",
    "load_program_graph",
    "save_program_graph",
    "ProgramExecutionSignature",
    "ProgramExecutionSignatureV2",
    "ProgramExecutionSignatureV3",
    "EmissionRouter",
    "EmissionRouterConfig",
    "EmissionRouterOutput",
    "build_stream_visibility",
    "stream_emit_mask",
    "ARTIOutput",
    "ARTILayer",
    "ProgramLayerResult",
    "ARTILatentTensorLayer",
    "ARTIDynamicStateLayer",
    "ARTIVirtualInterfaceMixer",
    "ARTILatentRecallField",
    "Retrieve",
    "FactorSpec",
    "RecallFormulaId",
    "RecallFormulaContract",
    "RecallFormulaExecutionSpec",
    "RecallFormulaLock",
    "validate_formula",
    "register_formula",
    "list_formulas",
    "describe_formula",
    "ARTIPhaseMixer",
    "ARTIResidualBlock",
    "ARTIHostBridge",
    "ARTISequenceBlock",
    "ARTIPooledBlock",
    "ARTIClassifier",
    "InspectionReport",
    "inspect",
    "LayeredRecallBudget",
    "LayeredRecallCandidate",
    "LayeredRecallCost",
    "LayeredRecallScore",
    "LayeredExecutionTraceCache",
    "candidates_within_budget",
    "estimate_layered_recall_cost",
    "pareto_layered_recall",
    "screen_layered_recall_candidate",
    "Layer",
    "FeatureConfig",
    "features",
    "profile",
    "layer_profiles",
    "Half",
    "UnFold",
    "Fold",
    "Pulse",
    "LearnedPulse",
    "FusionPulse",
    "RecallExecutor",
    "RetrieveExecutor",
    "VisualField",
    "VisualFieldOutput",
    "concat_visual_fields",
    "VisualScan",
    "VisualScanConfig",
    "VisualScanOutput",
    "PixelShiftObservation",
    "DEFAULT_PIXEL_SHIFTS",
    "pixel_shift_observe",
    "shift_and_add",
    "ARTIPlan",
    "ARTIPretrained",
    "ComponentPlan",
    "TrainingSpec",
    "PretrainedFitResult",
    "PretrainedExportResult",
    "pretrained",
    "from_pretrained",
    "validate_pretrained_lock",
    "model_structure_fingerprint",
    "ARTIProviderError",
    "PretrainedProvider",
    "ProviderInspection",
    "TorchProvider",
    "TransformersProvider",
    "PEFTProvider",
    "DiffusersProvider",
    "register_provider",
    "get_pretrained_provider",
    "provider_report",
    "RecallCapacityPlan",
    "RecallCapacityDecision",
    "module_structure_fingerprint",
    "module_behavior_fingerprint",
    "RECALL_BANK_ARTIFACT_KIND",
    "RECALL_BANK_ARTIFACT_VERSION",
    "RECALL_BANK_PROVENANCE_VERSION",
    "RecallBankAsset",
    "RecallBankAssembly",
    "RecallBankContract",
    "RecallBankError",
    "RecallBankLayout",
    "RecallBankMember",
    "RecallBankProvenance",
    "canonical_tensor_state_sha256",
    "create_recall_bank_contract",
    "save_recall_bank",
    "freeze_for_recall_bank",
    "inspect_recall_bank",
    "load_recall_bank",
    "migrate_recall_bank",
    "module_value_sha256",
    "recall_bank_parameter_names",
    "validate_recall_bank_contract",
    "MEMBRANE_STREAM_ASSISTANT_PUBLIC",
    "MEMBRANE_STREAM_ASSISTANT_INNER",
    "MEMBRANE_STREAM_NAMES",
    "MembraneRoutingConfig",
    "MembraneRoutingOutput",
    "MembraneContext",
    "MembraneVisibilityRouter",
    "membrane_public_emit_mask",
    "membrane_emit_tokens",
    "build_membrane_visibility",
    "append_membrane_tokens",
    "ParticipantContextTensors",
    "build_participant_context",
    "last_non_assistant_participant",
    "RuntimeVocabEncoder",
    "RuntimeVocabInput",
    "RuntimeVocabHead",
    "RuntimeVocabModel",
    "RuntimeVocabPulseAdapter",
    "LiteralVocabCache",
    "LiteralInput",
    "OutputLexiconContext",
    "LiteralOutputHead",
    "LiteralVocabModel",
    "LiteralSequenceDecoder",
    "LiteralSequenceOutput",
    "LiteralFitResult",
    "fit_literal_sequence",
    "attach_runtime_vocab_semantics",
    "flatten_vocab_tensor",
    "gather_runtime_vocab",
    "permute_runtime_vocab",
    "remap_token_ids",
    "PulseOutput",
    "PulseCompressor",
    "pulse_compress",
    "fixed_width_pulse_ids",
    "pulse_distinctness_report",
    "assert_pulse_distinct",
    "LatentDistinctnessReport",
    "latent_distinctness_report",
    "assert_latent_distinct",
    "BitmapTextConfig",
    "BitmapTextRenderer",
    "BitmapVocabReport",
    "render_text_bitmap",
    "render_text_vocab",
    "bitmap_vocab_report",
    "assert_bitmap_vocab_distinct",
    "TEXT_CONTROL_CHANNELS",
    "TEXT_IDENTITY_MODES",
    "TextControlKind",
    "TextTensorConfig",
    "TextTensorLayout",
    "TextTensorRenderer",
    "render_text_layout",
    "render_text_tensor",
    "SourceIntegrityBasis",
    "ARTI_ST_FORMAT",
    "ARTI_ST_FORMAT_VERSION",
    "ARTISaveResult",
    "ARTILoadResult",
    "save",
    "load",
    "SourceIntegrityCarrier",
    "SourceIntegrityReport",
    "SOURCE_INTEGRITY_MODES",
    "make_source_integrity_basis",
    "superpose_sources",
    "read_sources",
    "encode_source_tokens",
    "decode_source_tokens",
    "source_integrity_report",
    "source_integrity_loss",
    "assert_source_integrity",
    "source_basis_orthogonality_loss",
    "ARTIProject",
    "ARTIFitResult",
    "ADAPTER_STACK_FORMAT",
    "AdapterArtifactManifest",
    "BuildTaskSpec",
    "AdapterInsertionPlan",
    "FitPlugin",
    "FitProjectConfig",
    "MechanismOverrides",
    "RuntimeFieldConfig",
    "apply_mechanism_overrides",
    "resolve_fit_config_mechanism",
    "BackendCapabilities",
    "FitReportSummary",
    "FitTaskRecord",
    "ForwardProfile",
    "MechanismSummary",
    "ParameterSummary",
    "BatchSchema",
    "TensorField",
    "project",
    "reset_recall_queries",
    "fit",
    "apply_adapter",
    "apply_adapter_stack",
    "concatenate_adapter_banks",
    "set_adapter_bank_influences",
    "set_adapter_bank_weights",
    "compile_adapter_hotpaths",
    "set_adapter_scale",
    "set_retrieval_iteration_schedule",
    "set_retrieval_iteration_steps",
    "get_plugin",
    "load_fit_config",
    "template_fit_config",
    "validate_fit_config",
    "write_fit_config_template",
    "infer_batch_schema",
    "attention_mask_to_visibility",
    "capabilities",
    "list_profiles",
    "list_scales",
    "list_plugins",
    "resolve_objectives",
    "infer_objectives",
    "plan_provenance_fingerprint",
    "create_build_lock",
    "create_deployment_manifest",
    "create_task_graph_payload",
    "backend_capabilities",
    "doctor_report",
    "doctor_report_markdown",
    "validate_backend_capabilities",
    "write_doctor_report",
    "generate_capabilities_markdown",
    "generate_fit_config_schema",
    "generate_fit_config_schema_json",
    "generate_task_graph_schema",
    "generate_task_graph_schema_json",
    "packaged_fit_config_schema_json",
    "packaged_task_graph_schema_json",
    "write_generated_docs",
    "write_fit_config_schema",
    "write_task_graph_schema",
    "check_generated_docs",
    "check_fit_config_schema",
    "check_task_graph_schema",
    "validate_artifact",
    "validate_artifact_payload",
    "validate_build_lock",
    "validate_deployment_manifest",
    "validate_plan",
    "validate_plan_payload",
    "validate_task_graph",
    "validate_task_graph_payload",
    "write_task_graph_artifact",
    "cuda_device_report",
    "cuda_runtime_available",
    "cuda_smoke_report",
    "require_cuda",
    "virtual_recall_alignment_loss",
    "experiential_recall_alignment_loss",
    "recall_route_exterior_penalty",
    "experiential_recall_selectivity_loss",
    "available_backends",
    "planned_backends",
    "__version__",
]
