"""Run Formula Fabric with a route generated by existing Bank/Formula parts."""

import torch

from arti import alpha


def policy(seed: int) -> alpha.TypedBankFormulaTopologyPolicy:
    bank = alpha.TypedTopologyOperandBank(
        slots=8,
        key_dim=4,
        factor_dim=1,
        seed=seed,
        bank_id=f"route-{seed}",
    )
    return alpha.TypedBankFormulaTopologyPolicy(
        4, [bank], key_dim=4, query_seed=seed, diagnostics="none"
    )


program = alpha.FormulaFabricProgram(
    arena_capacity=5,
    feature_dim=4,
    steps=((alpha.FormulaInvocation(alpha.FormulaPrimitive.ADD, 2),),),
    domain="example",
)
candidate_mask = torch.zeros(1, 1, 2, 5, dtype=torch.bool)
candidate_mask[..., :2] = True
route_source = alpha.BankFormulaRouteSource(
    program,
    [policy(1), policy(2)],
    active_count=3,
    candidate_mask=candidate_mask,
)
compute = alpha.RoutedFormulaFabricCompute(
    alpha.FormulaFabricCompute(alpha.FormulaFabric(program), active_count=3),
    route_source,
)

value = torch.randn(2, 3, 4)
support = torch.ones(2, 3, dtype=torch.bool)
intervened = torch.tensor([[False, False, True]]).expand(2, -1)
workspace = alpha.ActiveWorkspace(value, support, support, intervened)
updated, info = compute(workspace, return_info=True)

print(updated.value.shape)
print(info.route_origin)
print(info.route.selected_input_slots)
