"""Canonical Python-owned contract for ARTI Web artifacts."""

from __future__ import annotations

from pathlib import Path


ARTI_WEB_FORMAT = "arti.web"
ARTI_WEB_FORMAT_VERSION = 2
ARTI_WEB_MANIFEST = "arti-web.json"
ARTI_WEB_MODEL = "model.onnx"
ARTI_WEB_LOCK = "arti-web.lock.json"


def artifact_schema() -> dict[str, object]:
    """Return the canonical JSON Schema for v2 manifests and locks."""

    file_record = {
        "type": "object",
        "required": ["sha256", "size"],
        "properties": {
            "sha256": {"type": "string", "pattern": "^[0-9a-f]{64}$"},
            "size": {"type": "integer", "minimum": 0},
        },
        "additionalProperties": False,
    }
    tensor = {
        "type": "object",
        "required": ["name", "dtype", "shape"],
        "properties": {
            "name": {"type": "string", "minLength": 1},
            "dtype": {"const": "float32"},
            "shape": {
                "type": "array",
                "minItems": 1,
                "items": {"oneOf": [{"type": "integer", "minimum": 0}, {"type": "string", "minLength": 1}]},
            },
        },
        "additionalProperties": False,
    }
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://arti.fit/schema/web-artifact-v2.json",
        "title": "ARTI Web Artifact v2",
        "$defs": {"file": file_record, "tensor": tensor},
        "type": "object",
        "required": ["manifest", "lock"],
        "properties": {
            "manifest": {
                "type": "object",
                "required": ["format", "format_version", "package_version", "producer", "module", "runtime", "inputs", "outputs", "files"],
                "properties": {
                    "format": {"const": ARTI_WEB_FORMAT},
                    "format_version": {"const": ARTI_WEB_FORMAT_VERSION},
                    "package_version": {"type": "string"},
                    "producer": {
                        "type": "object",
                        "required": ["backend", "graph_format"],
                        "properties": {"backend": {"type": "string"}, "graph_format": {"const": "onnx"}},
                        "additionalProperties": False,
                    },
                    "module": {
                        "type": "object",
                        "required": ["type", "config"],
                        "properties": {"type": {"type": "string", "minLength": 1}, "config": {"type": "object"}},
                        "additionalProperties": False,
                    },
                    "runtime": {
                        "type": "object",
                        "required": ["dtype", "opset_version", "execution_providers"],
                        "properties": {
                            "dtype": {"const": "float32"},
                            "opset_version": {"type": "integer", "minimum": 18},
                            "execution_providers": {"type": "array", "items": {"enum": ["webgpu", "wasm"]}, "minItems": 1},
                        },
                        "additionalProperties": False,
                    },
                    "inputs": {"type": "array", "items": {"$ref": "#/$defs/tensor"}, "minItems": 1},
                    "outputs": {"type": "array", "items": {"$ref": "#/$defs/tensor"}, "minItems": 1},
                    "files": {"type": "object", "required": [ARTI_WEB_MODEL], "additionalProperties": {"$ref": "#/$defs/file"}},
                },
                "additionalProperties": False,
            },
            "lock": {
                "type": "object",
                "required": ["format", "format_version", "manifest", "files"],
                "properties": {
                    "format": {"const": ARTI_WEB_FORMAT},
                    "format_version": {"const": ARTI_WEB_FORMAT_VERSION},
                    "manifest": {
                        "type": "object",
                        "required": ["file", "sha256"],
                        "properties": {"file": {"const": ARTI_WEB_MANIFEST}, "sha256": {"type": "string", "pattern": "^[0-9a-f]{64}$"}},
                        "additionalProperties": False,
                    },
                    "files": {"type": "object", "required": [ARTI_WEB_MODEL], "additionalProperties": {"$ref": "#/$defs/file"}},
                },
                "additionalProperties": False,
            },
        },
        "additionalProperties": False,
    }


def render_typescript_contract() -> str:
    """Render the TypeScript contract and validator from the Python schema."""

    return '''// Generated by arti.web.contract. Do not edit by hand.
export type ActiveARTIDevice = 'webgpu' | 'wasm';
export interface TensorContract { name: string; dtype: 'float32'; shape: Array<number | string>; }
export interface ARTIWebManifest {
  format: 'arti.web'; format_version: 2; package_version: string;
  producer: {backend: string; graph_format: 'onnx'};
  module: {type: string; config: Record<string, unknown>};
  runtime: {dtype: 'float32'; opset_version: number; execution_providers: ActiveARTIDevice[]};
  inputs: TensorContract[]; outputs: TensorContract[];
  files: Record<string, {sha256: string; size: number}>;
}
export interface ARTIWebLock {
  format: 'arti.web'; format_version: 2;
  manifest: {file: 'arti-web.json'; sha256: string};
  files: Record<string, {sha256: string; size: number}>;
}
const SHA256 = /^[0-9a-f]{64}$/;
export function parseManifest(value: unknown): ARTIWebManifest {
  const item = record(value, 'manifest');
  if (item.format !== 'arti.web') throw new Error('invalid ARTI Web manifest format');
  if (item.format_version !== 2) throw new Error('unsupported ARTI Web artifact version; re-export it with the current Python package');
  if (typeof item.package_version !== 'string') throw new Error('invalid ARTI Web package version');
  const producer = record(item.producer, 'producer');
  if (typeof producer.backend !== 'string' || producer.backend.length === 0 || producer.graph_format !== 'onnx') throw new Error('invalid ARTI Web producer');
  const module = record(item.module, 'module');
  if (typeof module.type !== 'string' || module.type.length === 0) throw new Error('invalid ARTI Web module type');
  record(module.config, 'module config');
  const runtime = record(item.runtime, 'runtime');
  if (runtime.dtype !== 'float32' || !Number.isInteger(runtime.opset_version) || Number(runtime.opset_version) < 18) throw new Error('invalid ARTI Web runtime contract');
  if (!Array.isArray(runtime.execution_providers) || !runtime.execution_providers.every((entry) => entry === 'webgpu' || entry === 'wasm')) throw new Error('invalid ARTI Web execution providers');
  tensorList(item.inputs, 'inputs'); tensorList(item.outputs, 'outputs');
  const files = record(item.files, 'files'); fileRecord(files['model.onnx'], 'model.onnx');
  return item as unknown as ARTIWebManifest;
}
export function parseLock(value: unknown): ARTIWebLock {
  const item = record(value, 'lock');
  if (item.format !== 'arti.web') throw new Error('invalid ARTI Web lock format');
  if (item.format_version !== 2) throw new Error('unsupported ARTI Web artifact version; re-export it with the current Python package');
  const manifest = record(item.manifest, 'manifest');
  if (manifest.file !== 'arti-web.json' || !isSha(manifest.sha256)) throw new Error('invalid ARTI Web lock manifest record');
  const files = record(item.files, 'files'); fileRecord(files['model.onnx'], 'model.onnx');
  return item as unknown as ARTIWebLock;
}
function tensorList(value: unknown, name: string): void {
  if (!Array.isArray(value) || value.length === 0) throw new Error(`invalid ARTI Web ${name} contract`);
  const names = new Set<string>();
  for (const entry of value) {
    const item = record(entry, name);
    if (typeof item.name !== 'string' || item.name.length === 0 || names.has(item.name) || item.dtype !== 'float32' || !Array.isArray(item.shape) || item.shape.length === 0) throw new Error(`invalid ARTI Web ${name} contract`);
    if (!item.shape.every((dim) => (Number.isSafeInteger(dim) && Number(dim) >= 0) || (typeof dim === 'string' && dim.length > 0))) throw new Error(`invalid ARTI Web ${name} shape`);
    names.add(item.name);
  }
}
function record(value: unknown, name: string): Record<string, unknown> { if (typeof value !== 'object' || value === null || Array.isArray(value)) throw new Error(`invalid ARTI Web ${name}`); return value as Record<string, unknown>; }
function isSha(value: unknown): value is string { return typeof value === 'string' && SHA256.test(value); }
function fileRecord(value: unknown, name: string): void { const item = record(value, name); if (!isSha(item.sha256) || !Number.isSafeInteger(item.size) || Number(item.size) < 0) throw new Error(`invalid ARTI Web ${name} file record`); }
'''


def write_typescript_contract(path: str | Path) -> Path:
    """Write the generated TypeScript contract to ``path``."""

    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_typescript_contract(), encoding="utf-8")
    return target
